# Generated by Django 4.1.2 on 2022-10-31 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=100)),
                ('encargado', models.CharField(max_length=100)),
                ('estado', models.BooleanField(default=False)),
            ],
        ),
    ]
