# Generated by Django 4.1.3 on 2022-11-01 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0003_lista_tablero_delete_actividad_lista_tablero'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tablero',
            name='encargado',
        ),
    ]
