# Generated by Django 4.1.3 on 2022-11-01 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0005_tablero_encargado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablero',
            name='encargado',
            field=models.CharField(max_length=255),
        ),
    ]
