# Generated by Django 4.1.3 on 2022-11-01 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0006_alter_tablero_encargado'),
    ]

    operations = [
        migrations.AddField(
            model_name='lista',
            name='imagen',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
