# Generated by Django 4.1.3 on 2022-11-07 14:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0007_lista_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='tablero',
            name='encargado',
        ),
        migrations.RemoveField(
            model_name='tablero',
            name='estado',
        ),
        migrations.AddField(
            model_name='tablero',
            name='fecha_vencimiento',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.DeleteModel(
            name='Lista',
        ),
    ]
