# Generated by Django 4.1.3 on 2022-11-07 14:27

import crud.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0008_estado_remove_tablero_encargado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tablero',
            name='fecha_vencimiento',
        ),
        migrations.AddField(
            model_name='tablero',
            name='due_date',
            field=models.DateTimeField(default=crud.models.one_week_hence),
        ),
    ]
