# Generated by Django 4.1.3 on 2022-11-07 14:33

import crud.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0009_remove_tablero_fecha_vencimiento_tablero_due_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('creado', models.DateTimeField(default=django.utils.timezone.now)),
                ('due_date', models.DateTimeField(default=crud.models.one_week_hence)),
                ('estado', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='Estado',
        ),
        migrations.RemoveField(
            model_name='tablero',
            name='creado',
        ),
        migrations.RemoveField(
            model_name='tablero',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='tablero',
            name='due_date',
        ),
        migrations.AddField(
            model_name='tarea',
            name='tablero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.tablero'),
        ),
    ]
