# Generated by Django 4.1.3 on 2022-11-07 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0010_tarea_delete_estado_remove_tablero_creado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='titulo',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
