# Generated by Django 4.1.3 on 2022-11-08 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0011_alter_tarea_titulo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarea',
            name='estado',
        ),
    ]
